'use client';

import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { TaxInput, TaxResult, formatPKR } from '../lib/taxEngine';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 12, fontFamily: 'Helvetica' },
  header: { fontSize: 20, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  sectionTitle: { fontSize: 14, marginTop: 15, marginBottom: 5, backgroundColor: '#f0f0f0', padding: 4, fontWeight: 'bold' },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: '#eeeeee' },
  label: { color: '#333333' },
  value: { fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 10, color: 'grey' }
});

interface PDFDocumentProps {
  input: TaxInput;
  result: TaxResult;
}

const TaxDocument = ({ input, result }: PDFDocumentProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>FBR Income Tax Return Summary</Text>
      
      <View style={styles.row}>
        <Text style={styles.label}>Tax Year:</Text>
        <Text style={styles.value}>{input.taxYear}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Taxpayer Type:</Text>
        <Text style={styles.value}>{input.taxpayerType.toUpperCase()}</Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Status:</Text>
        <Text style={styles.value}>{input.filerStatus.toUpperCase()} {input.isOverseas ? '(OVERSEAS)' : ''}</Text>
      </View>

      <Text style={styles.sectionTitle}>Income Summary</Text>
      <View style={styles.row}><Text style={styles.label}>Salary</Text><Text style={styles.value}>{formatPKR(input.salary)}</Text></View>
      <View style={styles.row}><Text style={styles.label}>Business (Net)</Text><Text style={styles.value}>{formatPKR(result.netBusinessIncome)}</Text></View>
      <View style={styles.row}><Text style={styles.label}>Rental (Net)</Text><Text style={styles.value}>{formatPKR(result.netRentalIncome)}</Text></View>
      <View style={styles.row}><Text style={styles.label}>Capital Gains</Text><Text style={styles.value}>{formatPKR(input.capitalGains)}</Text></View>
      <View style={styles.row}><Text style={[styles.label, { fontWeight: 'bold' }]}>TOTAL INCOME</Text><Text style={styles.value}>{formatPKR(result.totalIncome)}</Text></View>

      <Text style={styles.sectionTitle}>Deductions & Credits</Text>
      <View style={styles.row}><Text style={styles.label}>Zakat Paid</Text><Text style={styles.value}>{formatPKR(result.zakatDeduction)}</Text></View>
      <View style={styles.row}><Text style={[styles.label, { fontWeight: 'bold' }]}>TAXABLE INCOME</Text><Text style={styles.value}>{formatPKR(result.taxableIncome)}</Text></View>
      <View style={styles.row}><Text style={styles.label}>Tax Credits (Donation/Pension)</Text><Text style={styles.value}>{formatPKR(result.totalCredits)}</Text></View>

      <Text style={styles.sectionTitle}>Tax Computation</Text>
      <View style={styles.row}><Text style={styles.label}>Tax on Income (Slab: {result.currentSlab})</Text><Text style={styles.value}>{formatPKR(result.grossTax)}</Text></View>
      <View style={styles.row}><Text style={styles.label}>Less: Tax Credits</Text><Text style={styles.value}>- {formatPKR(result.totalCredits)}</Text></View>
      <View style={styles.row}><Text style={styles.label}>Less: WHT Paid</Text><Text style={styles.value}>- {formatPKR(result.totalWHTPaid)}</Text></View>
      
      <View style={[styles.row, { marginTop: 10, borderBottomWidth: 0 }]}>
        <Text style={[styles.label, { fontWeight: 'bold', fontSize: 14 }]}>
          {result.isRefund ? 'REFUND DUE:' : 'NET TAX PAYABLE:'}
        </Text>
        <Text style={[styles.value, { fontSize: 14 }]}>{formatPKR(Math.abs(result.netPayable))}</Text>
      </View>

      <Text style={styles.footer}>
        Generated by TaxBot.pk | For educational and guidance purposes only. Verify with a CA.
      </Text>
    </Page>
    
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>IRIS Filing Instructions</Text>
      <Text style={{ fontSize: 12, marginBottom: 10 }}>Follow these exact steps to file on the FBR IRIS Portal:</Text>
      
      <View style={{ marginBottom: 10 }}>
        <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>1. Login</Text>
        <Text>Go to iris.fbr.gov.pk and login with your NTN and password.</Text>
      </View>
      
      <View style={{ marginBottom: 10 }}>
        <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>2. Start Declaration</Text>
        <Text>Click "Declaration" &gt; "Income Tax Return" &gt; Select Tax Year {input.taxYear}.</Text>
      </View>
      
      <View style={{ marginBottom: 10 }}>
        <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>3. Enter Income</Text>
        <Text>Navigate to "Income" tabs and enter the Gross amounts as shown on Page 1.</Text>
      </View>
      
      <View style={{ marginBottom: 10 }}>
        <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>4. Tax Paid / Deductions</Text>
        <Text>Go to "Tax Chargeable/Payments" and enter your Withholding Tax (WHT) of PKR {result.totalWHTPaid.toLocaleString()} in the respective fields (e.g., Salary 149, Cash Withdrawal 231A).</Text>
      </View>
      
      <View style={{ marginBottom: 10 }}>
        <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>5. Verification & Submission</Text>
        <Text>Click "Calculate", verify the admitted tax matches PKR {result.netPayable > 0 ? result.netPayable.toLocaleString() : 0}. Generate a PSID to pay, or submit if zero/refund.</Text>
      </View>
    </Page>
  </Document>
);

export default function PDFDownload({ input, result }: PDFDocumentProps) {
  // react-pdf has hydration issues if rendered immediately, best to only mount after client load
  return (
    <div className="mt-4">
      <PDFDownloadLink
        document={<TaxDocument input={input} result={result} />}
        fileName={`TaxReturn_${input.taxYear}.pdf`}
        className="w-full block text-center bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 px-4 rounded-lg transition-colors shadow"
      >
        {({ loading }) => (loading ? 'Generating PDF...' : '📄 Download PDF Summary')}
      </PDFDownloadLink>
    </div>
  );
}
