import Link from 'next/link';

export default function NoticeGuide() {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white rounded-xl shadow-sm border border-slate-100 my-8">
      <div className="mb-8 border-b pb-6">
        <h1 className="text-3xl font-bold text-slate-800 mb-2">FBR Notice Guide</h1>
        <p className="text-slate-600">Don't panic! Here's what to do if you receive a notice from the Federal Board of Revenue.</p>
      </div>

      <div className="space-y-8">
        <section className="bg-rose-50 p-6 rounded-lg border border-rose-200">
          <h2 className="text-xl font-bold text-rose-800 mb-4 flex items-center">Why did I get a notice?</h2>
          <p className="text-rose-700 mb-4">Notices are often auto-generated by the FBR system. Common reasons include:</p>
          <ul className="list-disc pl-5 space-y-2 text-rose-800">
            <li>You bought or sold property/cars but are a non-filer.</li>
            <li>Your bank reported large transactions, but you haven't filed a return.</li>
            <li>You filed a return, but there is a mismatch between your declared income and your expenses (wealth statement).</li>
            <li>You missed the filing deadline (typically Sept 30th).</li>
          </ul>
        </section>

        <section className="bg-slate-50 p-6 rounded-lg border border-slate-200">
          <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center">Immediate Steps to Take</h2>
          <div className="space-y-4 text-slate-700">
            <div className="flex gap-4">
              <div className="bg-slate-200 text-slate-700 w-8 h-8 rounded-full flex items-center justify-center font-bold shrink-0">1</div>
              <div>
                <h3 className="font-bold">Check the deadline</h3>
                <p className="text-sm">Notices usually give you 15 to 30 days to respond. Note this date carefully to avoid further penalties.</p>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="bg-slate-200 text-slate-700 w-8 h-8 rounded-full flex items-center justify-center font-bold shrink-0">2</div>
              <div>
                <h3 className="font-bold">Login to IRIS</h3>
                <p className="text-sm">Go to <a href="https://iris.fbr.gov.pk" target="_blank" className="text-blue-600 hover:underline">iris.fbr.gov.pk</a>. Check your Inbox to read the official notice and see exactly which section of the law they are quoting (e.g., Section 114 for failure to file).</p>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="bg-slate-200 text-slate-700 w-8 h-8 rounded-full flex items-center justify-center font-bold shrink-0">3</div>
              <div>
                <h3 className="font-bold">File Your Return</h3>
                <p className="text-sm">If the notice is for non-filing, the simplest solution is to file your return immediately! Use our <Link href="/calculator" className="text-blue-600 hover:underline">Tax Calculator</Link> to prepare your numbers. Late filing carries a penalty of PKR 1,000 per month.</p>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-amber-50 p-6 rounded-lg border border-amber-200">
          <h2 className="text-xl font-bold text-amber-800 mb-4 flex items-center">When to hire a professional</h2>
          <p className="text-amber-800 mb-3">While you can reply to simple notices yourself through the IRIS portal, you should consult a Chartered Accountant or Tax Lawyer if:</p>
          <ul className="list-disc pl-5 space-y-2 text-amber-800 text-sm">
            <li>The notice demands a large sum of tax or penalty.</li>
            <li>The notice is for a tax audit (Section 177).</li>
            <li>You have undeclared foreign assets.</li>
            <li>You do not understand the legal jargon in the notice.</li>
          </ul>
        </section>
      </div>
      
      <div className="mt-8 pt-6 border-t flex justify-between">
        <Link href="/guide" className="text-blue-600 hover:underline">← Back to Guides</Link>
        <Link href="/chat" className="bg-blue-600 text-white px-6 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors">Ask AI Assistant</Link>
      </div>
    </div>
  );
}
